# Generated by Django 3.0.7 on 2020-06-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20200618_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('аниме', 'аниме'), ('биография', 'биография'), ('боевик', 'боевик'), ('вестерн', 'вестерн'), ('военный', 'военный'), ('детектив', 'детектив'), ('десткий', 'десткий'), ('для взрослых', 'для взрослых'), ('документальный', 'документальный'), ('драма', 'драма'), ('игра', 'игра'), ('история', 'история'), ('комедия', 'комедия'), ('концерт', 'концерт'), ('криминал', 'криминал'), ('мелодрама', 'мелодрама'), ('музыка', 'музыка'), ('мультфильм', 'мультфильм'), ('мюзикл', 'мюзикл'), ('новости', 'новости'), ('приключения', 'приключения'), ('реальное тв', 'реальное тв'), ('семейный', 'семейный'), ('спорт', 'спорт'), ('ток-шоу', 'ток-шоу'), ('триллер', 'триллер'), ('ужасы', 'ужасы'), ('фантастика', 'фантастика'), ('фентези', 'фентези'), ('церемония', 'церемония')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(to='movies.Country'),
        ),
    ]
