# Generated by Django 3.0.7 on 2020-06-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20200620_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='director',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='seasons_count',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='series_count',
        ),
        migrations.AddField(
            model_name='actor',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating_imdb',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
