# Generated by Django 3.0.7 on 2020-06-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20200623_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
