# Generated by Django 3.0.7 on 2020-06-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20200623_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-rating_kp']},
        ),
    ]
