# Generated by Django 3.0.7 on 2020-07-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20200624_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration_min',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
