# Generated by Django 3.0.7 on 2020-07-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20200709_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-rating_kp', 'id']},
        ),
    ]
